PACKAGE_NAME="ionopi"
PACKAGE_VERSION="$(cat VERSION)"

BUILT_MODULE_NAME[0]="ionopi"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"

MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make clean KERNELRELEASE=${kernelver}"

POST_INSTALL="./dkms-post-install.sh"
PRE_REMOVE="./dkms-pre-remove.sh"
