PACKAGE_NAME="ionopi"
PACKAGE_VERSION="1.24"

# How to build and clean the module
MAKE="make -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
CLEAN="make -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

# Name of the module (without .ko extension)
BUILT_MODULE_NAME[0]="ionopi"

# Where the .ko file will be located after build
BUILT_MODULE_LOCATION="."

# Where to install the module within /lib/modules/<kernel>
DEST_MODULE_LOCATION[0]="/extra"

# Automatically rebuild and install this module when kernels are updated
AUTOINSTALL="yes"
