name: Build Kernel Module

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: sfera-labs/sl-kmod-commons/.github/workflows/kmod-build.yml@main
    with:
      newest_lines_count: 3
      build_families: 'rpi,ubuntu'
      module_path: '.'
